version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    container_name: mysql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - web
    container_name: nginx

  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mysql
    container_name: web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    depends_on:
      - mysql